---
title: "REPORTE PRÁCTICA 6:Genómica poblacional y ancestría"
author: "Jacqueline Vasquez"
date: "12-04-2021"
output:
  html_document:
    code_folding: hide
    pdf_document: default
    toc: true
    toc_depth: 5
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readr)
library(dplyr)
library(tidyverse)
library(cowplot)
library(e1071)
```

### 4. ANÁLISIS DE DIVERSIDAD
#### 4.4 Gráficos de heterogocidad individual, diversidad de nucleótidos y Desequilibrio de ligamiento (LD).
```{r}
EU <- read_delim("EU.geno.ld", delim = "\t")
OC <- read_delim("OC.geno.ld", delim = "\t")
US <- read_delim("US.geno.ld", delim = "\t")

EU$dist <- ceiling((EU$POS2 - EU$POS1)/1000)*1000
OC$dist <- ceiling((OC$POS2 - OC$POS1)/1000)*1000
US$dist <- ceiling((US$POS2 - US$POS1)/1000)*1000

EU2 <- group_by(EU,dist) %>%
  summarise(meanR2 = mean(`R^2`))

OC2 <- group_by(OC,dist) %>%
  summarise(meanR2 = mean(`R^2`))
  
US2 <- group_by(US,dist) %>%
  summarise(meanR2 = mean(`R^2`))  

dd <- bind_rows(EU2,OC2,US2)

dd$pop <- rep(c("EU","OC","US"),c(nrow(EU2),nrow(OC2),nrow(US2))) 

write_csv(dd,"EU_OC_US.windowed.ld.csv")
```
```{r}
# Heterogenecidad individual
het <- read_delim("EU_OC_US.het",delim = "\t")
het
het$Heterozygosity <- 1-(het$`O(HOM)`/het$N_SITES) 
het$Population <- c(rep("EU",3),rep("OC",3),rep("US",3))
A <- ggplot(het,aes(x = Population, y = Heterozygosity, col = Population)) +
  geom_point()+
  theme_bw()+
  theme(legend.position = "none")+
  xlab("")
A
```


```{r}
# Diversidad de nucleótidos 
pi_EU <- read_delim("EU.windowed.pi",delim = "\t")
pi_EU
pi_OC <- read_delim("OC.windowed.pi",delim = "\t")
pi_OC
pi_US <- read_delim("US.windowed.pi",delim = "\t")
pi_US
pi_all <- bind_rows(pi_EU,pi_OC,pi_US)
pi_all$Population<-c(rep("EU",nrow(pi_EU)),rep("OC",nrow(pi_OC)),rep("US",nrow(pi_US)))

B <- ggplot(pi_all,aes(x = Population, y = PI, col = Population))+
      geom_jitter(col = "grey",width = 0.1)+ 
      geom_boxplot(notch = T, alpha = 0,outlier.shape = NA)+ 
      theme_bw()+
      theme(legend.position = "none")+
      xlab("")+
      ylab(expression(pi))
B

```

```{r}
# Desequilibrio de ligamiento
ld <- read_csv("EU_OC_US.windowed.ld.csv")
ld
C <- ggplot(ld,aes(x = dist/1000, y = meanR2, col = pop)) +
      geom_point()+
      geom_line()+
      theme_bw()+
      xlab("Distance (kb)")+
      ylab(expression(R^2))+
      scale_colour_discrete(name = "Population")
C
```


```{r}
# GRAFICOS PANELES MULTIPLES 

top_row <- plot_grid(A,B,labels = "AUTO")
plot_grid(top_row,C,nrow = 2,labels = c("","C"))
```


### 5. ANÁLISIS DE ESTRUCTURA POBLACIONAL
##### 5.7 - Gráficos de PCA con R

```{r}
#GRAFCOS DE PCA
pca1 <- read_delim("EU_OC_US.FilteredPrunedUnrel.eigenvec", delim = " ",col_names = F)
    head(pca1)
```

```{r}
    colnames(pca1) <- c("Population","Individual",paste0("PC",c(1:4)))
    head(pca1)
    
        mycols <- c("#a6cee3",
              "#1f78b4",
              "#b2df8a",
              "#33a02c",
              "#fb9a99",
              "#e31a1c",
              "#fdbf6f",
              "#ff7f00",
              "#cab2d6")

    D <- ggplot(pca1,aes(x = PC1,y = PC2,col = Population))+
      geom_point()+
      theme_bw()+
      scale_colour_manual(values = mycols)
    D
```


### 6. ANÁLISIS DE ADMIXTURE 
#### 6.3 - Gráficos de ADMIXTURE para 2, 4 y 6 poblaciones

```{r}
# GRAFICOS DE ADMIXTURE PARA 2, 4 y 6 POBLACIONES
source("Admixture_plot.R")

    pops <- read_delim("EU_OC_US.Thinned.fam", delim = " ",col_names = F)

    K2 <- read_delim("EU_OC_US.Thinned.2.Q", delim = " ",col_names = F)
    E <- admixtureplot(str_out = K2,k = 2, pops = pops, xaxis = F)
    E
```
```{r}
  K4 <- read_delim("EU_OC_US.Thinned.4.Q", delim = " ", col_names = F)
    G <- admixtureplot(str_out = K4,k = 4, pops = pops, xaxis = F)
    G
    
```
```{r}
    K6 <- read_delim("EU_OC_US.Thinned.6.Q", delim = " ", col_names = F)
    H <- admixtureplot(str_out = K6,k = 6, pops = pops, xaxis = T)
    H
```
```{r}
#GRÁFICOS 
plot_grid(E,G,H,labels = "AUTO")
```
